### ISSUE TITLE
Unable to manually start a smoke test in concourse

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-aot-smoke-tests#157]
When scheduling a new build for a smoke test in concourse, it waits for a resource named `time-<name-of-the-test>`.

![image](https://user-images.githubusercontent.com/98899556/204557901-8eec5aba-baed-4159-80a8-0e0cd4e8ac10.png)

I guess this is a side effect of how the "schedule on some random time in the night" is set up.

**Comment by wilkinsona** [comment]
It works now that `time-spring-pulsar-app-test` has produced its first version. In other words, this is only a problem when a new smoke test has been added and you want to run it immediately rather than waiting for it to be scheduled. I'm not sure that there's anything that we can (easily) do about that.

**Comment by mhalbritter** [comment]
Ah, I guess we can live with that.
