### ISSUE TITLE
Reduce how often CI builds download Gradle

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-aot-smoke-tests#191]
Judging by some recent CI failures due to the download of  https://services.gradle.org/distributions/gradle-7.6-bin.zip timing out, CI builds are downloading Gradle more often than they should. We could try:

1. Caching the `.gradle` directory across runs
2. Pre-installing Gradle in the CI container image

**Comment by philwebb** [comment]
I think we already call [this function](https://github.com/spring-io/concourse-java-scripts/blob/148beadeadd0d8182f70b41f332d9866bea71843/concourse-java.sh#L15-L22) to setup a `.gradle` symlink and then our task [should use that as a cache](https://github.com/spring-projects/spring-boot/blob/5280cfeec053d94dfca1314e415e8310d67a0b5f/ci/tasks/build-project.yml#L9).

**Comment by philwebb** [comment]
Oddly, if I `fly hijack` I see that the `gradle` folder isn't a symlink. It's also empty.

**Comment by philwebb** [comment]
Sorry for the noise, I thought this was a Spring Boot issue 🤦.

It turns out we do have a similar issue with Spring Boot which is caused by us creating a `.gradle` folder in the CI image. This stops the symlink from being created. I think AOT tests has the same problem looking at [these lines](https://github.com/spring-projects/spring-aot-smoke-tests/blob/597ea03cb1f5f84a2840d57d4c0d797a9fcfe490/ci/images/setup.sh#L58-L59)

**Comment by wilkinsona** [comment]
Thanks, @philwebb. That does indeed look like the same problem.
